<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\ProjectType;
use App\Models\ProjectStatus;
use App\Models\Department;
use App\Models\User;
use App\Models\LguSector;
use App\Models\Province;
use App\Models\Municipality;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Creates 50 realistic projects for CARAGA Region XIII
     * - 32 Economic Services (ES) projects
     * - 18 Infrastructure & Environmental Management (IEM) projects
     */
    public function run(): void
    {
        DB::transaction(function () {
            // Get reference data
            $projectTypes = ProjectType::all()->keyBy('name');
            $projectStatuses = ProjectStatus::all()->keyBy('name');
            $departments = Department::all()->keyBy('name');

            // Get LGU Sectors (RA 7160)
            $sectors = LguSector::all()->keyBy('code');
            $es = $sectors['ES'] ?? null; // Economic Services
            $iem = $sectors['IEM'] ?? null; // Infrastructure & Environmental Management

            // Get Provinces and Municipalities
            $provinces = Province::all()->keyBy('name');
            $municipalities = Municipality::all()->keyBy('name');

            $projects = [
                // ========================================
                // ECONOMIC SERVICES (ES) - 32 PROJECTS
                // ========================================

                // RICE PROGRAM (4 projects)
                [
                    'title' => 'Hybrid Rice Production Enhancement in Agusan del Norte',
                    'description' => 'Distribution of 50 tons of certified hybrid rice seeds to 2,500 farmers across 15 municipalities. Includes training on modern rice farming techniques, provision of farm inputs, and establishment of 20 demonstration farms. Target yield increase: 25%.',
                    'department_id' => $departments['Rice Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Crop Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Butuan']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Poblacion',
                    'budget' => 45000000.00,
                    'start_date' => Carbon::parse('2024-01-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Rice Seed Production and Distribution - Agusan del Sur',
                    'description' => 'Establishment of rice seed farms covering 200 hectares. Production of quality certified seeds for distribution to CARAGA farmers. Includes seed storage facilities, certification support, and quality testing laboratory.',
                    'department_id' => $departments['Rice Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Crop Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bayugan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Agustin',
                    'budget' => 38000000.00,
                    'start_date' => Carbon::parse('2024-02-01'),
                    'end_date' => Carbon::parse('2026-01-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Integrated Rice-Fish Farming System Development',
                    'description' => 'Promotion of rice-fish farming integration in 500 hectares of rice fields. Provision of tilapia fingerlings, technical training, and market support. Increases farmer income by 40% through dual production.',
                    'department_id' => $departments['Rice Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Crop Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bunawan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Consuelo',
                    'budget' => 28000000.00,
                    'start_date' => Carbon::parse('2024-03-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Rice Technology Demonstration and Training Program',
                    'description' => 'Establishment of 30 rice technology demonstration farms showcasing best practices in rice cultivation, pest management, and mechanization. Training for 1,500 farmers on modern rice production techniques.',
                    'department_id' => $departments['Rice Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Capacity Building']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Pedro',
                    'budget' => 19000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2025-06-30'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // HIGH-VALUE CROPS (8 projects)
                [
                    'title' => 'CARAGA Cacao Development Program - Surigao del Sur',
                    'description' => 'Large-scale cacao development covering 1,500 hectares. Provision of 300,000 quality cacao seedlings, technical assistance, fermentation and drying facilities, and market linkages with chocolate manufacturers. Target: 800 cacao farmer beneficiaries.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Tandag']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Awasian',
                    'budget' => 62000000.00,
                    'start_date' => Carbon::parse('2023-03-01'),
                    'end_date' => Carbon::parse('2026-02-28'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Coffee Production and Processing - Mountain Communities',
                    'description' => 'Arabica and Robusta coffee production in upland areas. Establishment of 800 hectares coffee plantations, provision of 150,000 coffee seedlings, installation of coffee processing equipment, barista training, and cafe establishment support.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'La Caridad',
                    'budget' => 38000000.00,
                    'start_date' => Carbon::parse('2024-02-01'),
                    'end_date' => Carbon::parse('2027-01-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Abaca Fiber Production Enhancement - Dinagat Islands',
                    'description' => 'Revitalization of abaca industry with tissue-cultured disease-resistant planting materials. Distribution of 200,000 abaca seedlings, establishment of decorticating facilities, fiber processing training, and market development. Coverage: 1,200 hectares.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['San Jose']->id ?? null,
                    'province_id' => $provinces['Dinagat Islands']->id ?? null,
                    'barangay' => 'White Beach',
                    'budget' => 28000000.00,
                    'start_date' => Carbon::parse('2024-04-01'),
                    'end_date' => Carbon::parse('2026-03-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Coconut Rehabilitation and Replanting Program - Region-Wide',
                    'description' => 'Rehabilitation of 5,000 hectares of senile and typhoon-damaged coconut farms. Distribution of 500,000 hybrid coconut seedlings, intercropping support, coco-net installation, farm insurance, and coconut product diversification training. Benefits 3,500 farmers.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Crop Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bislig']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Mangagoy',
                    'budget' => 95000000.00,
                    'start_date' => Carbon::parse('2023-08-01'),
                    'end_date' => Carbon::parse('2026-07-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Banana Production and Export Readiness Program',
                    'description' => 'Development of export-quality banana production in 600 hectares. Provision of tissue-cultured banana seedlings, drip irrigation systems, organic fertilizers, GlobalGAP certification support, and export market linkages.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['Planning']->id ?? null,
                    'municipality_id' => $municipalities['Cabadbaran']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Bayabas',
                    'budget' => 42000000.00,
                    'start_date' => Carbon::parse('2025-01-01'),
                    'end_date' => Carbon::parse('2027-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Pineapple Production and Processing Development',
                    'description' => 'Establishment of 400 hectares pineapple plantations using improved varieties. Includes drip irrigation, organic farming practices, pineapple processing facility for juice and dried products, and market development support.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['Under Review']->id ?? null,
                    'municipality_id' => $municipalities['Bayugan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Poblacion',
                    'budget' => 35000000.00,
                    'start_date' => Carbon::parse('2025-02-01'),
                    'end_date' => Carbon::parse('2027-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Rubber Plantation Development Project',
                    'description' => 'Expansion of rubber production in suitable areas covering 800 hectares. Distribution of high-yielding rubber clones, establishment of rubber nurseries, tapping training, and latex processing facilities.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['San Francisco']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Hubang',
                    'budget' => 47000000.00,
                    'start_date' => Carbon::parse('2024-01-15'),
                    'end_date' => Carbon::parse('2028-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Dragon Fruit and Exotic Fruits Production',
                    'description' => 'Development of dragon fruit, passion fruit, and rambutan production in 250 hectares. Provision of planting materials, trellising systems, organic fertilizers, post-harvest handling training, and premium market access.',
                    'department_id' => $departments['High-Value Crops Development Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['High-Value Crops']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Surigao City']->id ?? null,
                    'province_id' => $provinces['Surigao del Norte']->id ?? null,
                    'barangay' => 'Washington',
                    'budget' => 26000000.00,
                    'start_date' => Carbon::parse('2024-03-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // LIVESTOCK DEVELOPMENT (6 projects)
                [
                    'title' => 'Cattle Dispersal and Fattening Program - Agusan Valley',
                    'description' => 'Dispersal of 500 heads of quality cattle breeds to 100 farmer cooperatives. Construction of cattle housing, pasture development with improved grasses, veterinary services, feeds provision, and market linkages with meat processors.',
                    'department_id' => $departments['Livestock Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Livestock Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bunawan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Consuelo',
                    'budget' => 42000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Swine Production and Biosecurity Enhancement',
                    'description' => 'Construction of 50 biosecure piggery units with ASF-prevention measures. Provision of quality breeding stock (300 heads), biosecurity training, feeds formulation, waste management systems, and veterinary support.',
                    'department_id' => $departments['Livestock Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Livestock Development']->id ?? null,
                    'project_status_id' => $projectStatuses['Delayed']->id ?? null,
                    'municipality_id' => $municipalities['Cabadbaran']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Del Pilar',
                    'budget' => 35000000.00,
                    'start_date' => Carbon::parse('2023-10-01'),
                    'end_date' => Carbon::parse('2025-09-30'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Goat and Sheep Livelihood - Upland Communities',
                    'description' => 'Distribution of 1,000 heads improved goat breeds and 500 sheep to upland families. Construction of housing facilities, forage establishment, animal health services, meat processing training. Focus on women and IP participation.',
                    'department_id' => $departments['Livestock Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Livestock Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['San Francisco']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Hubang',
                    'budget' => 18000000.00,
                    'start_date' => Carbon::parse('2024-03-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Native Chicken Production Enhancement Program',
                    'description' => 'Development of native chicken industry with improved breeds. Distribution of 20,000 native chicken chicks, construction of 200 chicken houses, feeds production training, and establishment of buying stations.',
                    'department_id' => $departments['Livestock Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Livestock Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Tandag']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Bongtud',
                    'budget' => 15000000.00,
                    'start_date' => Carbon::parse('2024-02-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Carabao Development and Breeding Program',
                    'description' => 'Improvement of carabao population through artificial insemination and breeding. Distribution of 200 improved carabao breeds, AI services, pasture improvement, and dairy processing training for milk production.',
                    'department_id' => $departments['Livestock Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Livestock Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Pedro',
                    'budget' => 23000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Duck Production and Balut Industry Development',
                    'description' => 'Development of duck raising for balut and salted egg production. Distribution of 10,000 duck layers, construction of duck houses, balut processing training, and market development support.',
                    'department_id' => $departments['Livestock Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Livestock Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Butuan']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Libertad',
                    'budget' => 12000000.00,
                    'start_date' => Carbon::parse('2024-04-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // FISHERIES AND AQUATIC RESOURCES (4 projects)
                [
                    'title' => 'Mariculture Development - Surigao del Norte Coastal Areas',
                    'description' => 'Marine cage aquaculture for milkfish, grouper, and seaweed farming. Installation of 100 marine cages (10x10m each), seaweed farming training covering 50 hectares, post-harvest facilities, and market support. Benefits 300 fisherfolk families.',
                    'department_id' => $departments['Fisheries and Aquatic Resources Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Fisheries Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Surigao City']->id ?? null,
                    'province_id' => $provinces['Surigao del Norte']->id ?? null,
                    'barangay' => 'Mabua',
                    'budget' => 32000000.00,
                    'start_date' => Carbon::parse('2023-11-01'),
                    'end_date' => Carbon::parse('2025-10-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Freshwater Aquaculture and Tilapia Production',
                    'description' => 'Establishment of 80 fishpond units (0.5 hectare each) and tilapia cage culture in lakes and reservoirs. Provision of quality tilapia fingerlings, feeds, technical training, and marketing support. Target: 200 farmer families.',
                    'department_id' => $departments['Fisheries and Aquatic Resources Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Fisheries Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bunawan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Libertad',
                    'budget' => 24000000.00,
                    'start_date' => Carbon::parse('2024-02-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Mud Crab Fattening and Mangrove Aquaculture',
                    'description' => 'Development of mud crab fattening in mangrove areas using bamboo cages. Provision of crablets, fattening cages (5,000 units), feeds, and marketing support. Promotes sustainable mangrove-based aquaculture.',
                    'department_id' => $departments['Fisheries and Aquatic Resources Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Fisheries Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bislig']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Mangagoy',
                    'budget' => 16000000.00,
                    'start_date' => Carbon::parse('2024-03-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Bangus (Milkfish) Hatchery and Fry Production',
                    'description' => 'Establishment of bangus hatchery facility to ensure stable supply of quality fry. Hatchery capacity: 10 million fry annually. Includes broodstock management, laboratory equipment, and technician training.',
                    'department_id' => $departments['Fisheries and Aquatic Resources Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Fisheries Development']->id ?? null,
                    'project_status_id' => $projectStatuses['Planning']->id ?? null,
                    'municipality_id' => $municipalities['San Jose']->id ?? null,
                    'province_id' => $provinces['Dinagat Islands']->id ?? null,
                    'barangay' => 'White Beach',
                    'budget' => 28000000.00,
                    'start_date' => Carbon::parse('2025-01-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // AGRIBUSINESS AND MARKETING (3 projects)
                [
                    'title' => 'Regional Agri-Tourism Development Program',
                    'description' => 'Development of 15 agri-tourism sites showcasing CARAGA agricultural products. Establishment of farm parks, eco-tourism facilities, agri-food hubs, farm restaurants, and tourism packages. Promotes agri-tourism integration.',
                    'department_id' => $departments['Agribusiness and Marketing Assistance Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Sustainable Agriculture']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Tandag']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Awasian',
                    'budget' => 38000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'CARAGA Food Processing and Product Development',
                    'description' => 'Establishment of 10 community food processing centers. Equipment for fruit processing, dried products, condiments, and native delicacies. Product development, food safety training, packaging design, and branding support.',
                    'department_id' => $departments['Agribusiness and Marketing Assistance Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Post-Harvest Facilities']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Butuan']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Poblacion',
                    'budget' => 30000000.00,
                    'start_date' => Carbon::parse('2024-02-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Digital Agriculture and E-Commerce Platform',
                    'description' => 'Development of CARAGA agri e-commerce platform connecting farmers to markets. Mobile app development, digital marketing training, online payment systems, logistics support, and buyer-seller matching services.',
                    'department_id' => $departments['Agribusiness and Marketing Assistance Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Capacity Building']->id ?? null,
                    'project_status_id' => $projectStatuses['Under Review']->id ?? null,
                    'municipality_id' => $municipalities['Surigao City']->id ?? null,
                    'province_id' => $provinces['Surigao del Norte']->id ?? null,
                    'barangay' => 'Washington',
                    'budget' => 22000000.00,
                    'start_date' => Carbon::parse('2025-03-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // FIELD OPERATIONS (2 projects)
                [
                    'title' => 'Farmer Field School and Extension Services',
                    'description' => 'Establishment of 100 Farmer Field Schools across CARAGA. Training for 5,000 farmers on crop production, pest management, climate-smart agriculture, organic farming, and agribusiness. Includes certified trainers and demonstration farms.',
                    'department_id' => $departments['Field Operations Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Capacity Building']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bayugan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Agustin',
                    'budget' => 28000000.00,
                    'start_date' => Carbon::parse('2023-09-01'),
                    'end_date' => Carbon::parse('2025-08-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Climate-Smart Agriculture Adoption Program',
                    'description' => 'Promotion of climate-resilient farming practices. Training on water-saving techniques, drought-tolerant varieties, weather forecasting tools, crop insurance, and disaster preparedness. Covers 3,000 hectares in vulnerable areas.',
                    'department_id' => $departments['Field Operations Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Sustainable Agriculture']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Cabadbaran']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Bayabas',
                    'budget' => 24000000.00,
                    'start_date' => Carbon::parse('2024-01-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // ORGANIC AGRICULTURE (2 projects)
                [
                    'title' => 'Organic Agriculture Development and Certification',
                    'description' => 'Promotion of organic farming with certification support. Training on organic production methods for 800 farmers, provision of organic inputs, composting facilities, organic certification assistance, and organic market development. Target: 2,000 hectares certified.',
                    'department_id' => $departments['Organic Agriculture Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Sustainable Agriculture']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Tandag']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Bongtud',
                    'budget' => 32000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Vermicomposting and Organic Fertilizer Production',
                    'description' => 'Establishment of 50 vermicomposting facilities for organic fertilizer production. Distribution of African night crawlers, composting beds, training on vermicast production, and market linkages for organic fertilizer.',
                    'department_id' => $departments['Organic Agriculture Program']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Sustainable Agriculture']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'La Caridad',
                    'budget' => 14000000.00,
                    'start_date' => Carbon::parse('2024-03-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // RESEARCH AND DEVELOPMENT (2 projects)
                [
                    'title' => 'Climate-Resilient Crop Varieties Research',
                    'description' => 'Research and testing of climate-resilient crop varieties adapted to CARAGA. Variety trials for drought-tolerant rice, flood-resistant corn, pest-resistant vegetables. Farmer participatory research and demonstration farms. Partnership with PhilRice and universities.',
                    'department_id' => $departments['Research and Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Research and Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Butuan']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Banza',
                    'budget' => 22000000.00,
                    'start_date' => Carbon::parse('2023-05-01'),
                    'end_date' => Carbon::parse('2026-04-30'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Indigenous Knowledge and Traditional Farming Systems',
                    'description' => 'Documentation and validation of indigenous agricultural practices. Research on traditional crop varieties, indigenous pest management, and sustainable farming systems. Integration with modern science for improved productivity.',
                    'department_id' => $departments['Research and Development Division']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Research and Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['San Francisco']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Hubang',
                    'budget' => 16000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // AGRICULTURAL EXTENSION (1 project)
                [
                    'title' => 'Agricultural Extension Worker Capacity Building',
                    'description' => 'Training and certification of 200 agricultural extension workers (AEWs) across CARAGA. Advanced training on extension methodologies, digital tools, farmer coaching, and community organizing. Provision of tablets, motorcycles, and field equipment.',
                    'department_id' => $departments['Agricultural Extension Services']->id ?? null,
                    'sector_id' => $es?->id,
                    'project_type_id' => $projectTypes['Capacity Building']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Surigao City']->id ?? null,
                    'province_id' => $provinces['Surigao del Norte']->id ?? null,
                    'barangay' => 'Washington',
                    'budget' => 18000000.00,
                    'start_date' => Carbon::parse('2024-02-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // ================================================================
                // INFRASTRUCTURE & ENVIRONMENTAL MANAGEMENT (IEM) - 18 PROJECTS
                // ================================================================

                // IRRIGATION SYSTEMS (5 projects)
                [
                    'title' => 'Irrigation System Rehabilitation - Agusan del Sur',
                    'description' => 'Rehabilitation of existing irrigation systems serving 3,200 hectares of rice farmlands. Canal lining (15km), installation of water control structures (50 units), repair of headworks, and farmer irrigation association strengthening. Improves water efficiency by 35%.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bayugan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Agustin',
                    'budget' => 78000000.00,
                    'start_date' => Carbon::parse('2023-06-01'),
                    'end_date' => Carbon::parse('2025-05-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Small-Scale Irrigation Development - Dinagat Islands',
                    'description' => 'Construction of 10 small-scale irrigation systems (average 200 ha each) for rice and vegetable production. Includes shallow tube wells, solar-powered pumps, distribution pipes, and water management training.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['San Jose']->id ?? null,
                    'province_id' => $provinces['Dinagat Islands']->id ?? null,
                    'barangay' => 'White Beach',
                    'budget' => 45000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Micro-Irrigation and Drip Systems for Vegetables',
                    'description' => 'Installation of drip irrigation systems in 500 hectares of vegetable farms. Provision of drip lines, filters, fertigation equipment, and water source development. Training on water-efficient farming practices.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Tandag']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Awasian',
                    'budget' => 32000000.00,
                    'start_date' => Carbon::parse('2024-02-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Dam and Reservoir Construction - Multi-Purpose',
                    'description' => 'Construction of 3 small earth dams for irrigation and water supply. Total storage capacity: 5 million cubic meters. Serves irrigation for 1,500 hectares and potable water for 10,000 households.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['Planning']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Pedro',
                    'budget' => 150000000.00,
                    'start_date' => Carbon::parse('2025-06-01'),
                    'end_date' => Carbon::parse('2028-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Solar-Powered Irrigation Pumping Stations',
                    'description' => 'Installation of 30 solar-powered irrigation pumping stations in off-grid agricultural areas. Each station includes solar panels (5kW), submersible pumps, batteries, and control systems. Reduces dependence on diesel.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['Under Review']->id ?? null,
                    'municipality_id' => $municipalities['Bunawan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Consuelo',
                    'budget' => 42000000.00,
                    'start_date' => Carbon::parse('2025-01-01'),
                    'end_date' => Carbon::parse('2026-06-30'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // FARM-TO-MARKET ROADS (4 projects)
                [
                    'title' => 'Farm-to-Market Road Network - Phase II (Agusan del Sur)',
                    'description' => 'Construction of 45 kilometers of farm-to-market roads connecting agricultural areas to trading centers. Includes concrete pavement (6m width), 8 bridges (average 15m), drainage systems, and road signage. Reduces transport cost by 40%.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'San Pedro',
                    'budget' => 125000000.00,
                    'start_date' => Carbon::parse('2023-07-01'),
                    'end_date' => Carbon::parse('2025-06-30'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Farm-to-Market Road Improvement - Surigao del Norte',
                    'description' => 'Rehabilitation and improvement of 35 kilometers of existing farm roads. Concrete overlay, shoulder improvements, culvert installations, and road widening. Connects cacao and coconut farms to processing centers.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Surigao City']->id ?? null,
                    'province_id' => $provinces['Surigao del Norte']->id ?? null,
                    'barangay' => 'Mabua',
                    'budget' => 95000000.00,
                    'start_date' => Carbon::parse('2024-01-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Upland Road Access Development',
                    'description' => 'Construction of 25 kilometers of access roads to upland coffee, rubber, and vegetable farms. Gravel pavement, retaining walls, drainage, and erosion control measures. Opens 5,000 hectares of agricultural land.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['Delayed']->id ?? null,
                    'municipality_id' => $municipalities['San Francisco']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Hubang',
                    'budget' => 65000000.00,
                    'start_date' => Carbon::parse('2023-09-01'),
                    'end_date' => Carbon::parse('2025-08-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Bridge Construction for Agricultural Transport',
                    'description' => 'Construction of 12 bridges (average 20m span) along key agricultural routes. Reinforced concrete bridges designed for 20-ton capacity. Ensures year-round access to farms during rainy season.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['Planning']->id ?? null,
                    'municipality_id' => $municipalities['Bayugan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Poblacion',
                    'budget' => 88000000.00,
                    'start_date' => Carbon::parse('2025-03-01'),
                    'end_date' => Carbon::parse('2027-02-28'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // POST-HARVEST FACILITIES (5 projects)
                [
                    'title' => 'Regional Rice Processing Complex - Butuan City',
                    'description' => 'Modern rice processing facility with 5 tons/hour milling capacity. Includes rice mill, grain dryers (100 tons/day), warehouse (5,000 tons), quality testing lab, packaging equipment, and loading bay. Central hub for CARAGA rice.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Post-Harvest Facilities']->id ?? null,
                    'project_status_id' => $projectStatuses['Planning']->id ?? null,
                    'municipality_id' => $municipalities['Butuan']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Libertad',
                    'budget' => 85000000.00,
                    'start_date' => Carbon::parse('2025-01-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Cold Storage and Pack House Network',
                    'description' => 'Construction of 5 cold storage facilities (200 tons each) and pack houses for fruits and vegetables. Each includes cold rooms (0-4°C), pre-cooling areas, sorting/grading equipment, and refrigerated transport (5 units). Reduces losses by 40%.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Post-Harvest Facilities']->id ?? null,
                    'project_status_id' => $projectStatuses['Under Review']->id ?? null,
                    'municipality_id' => $municipalities['Cabadbaran']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Bayabas',
                    'budget' => 68000000.00,
                    'start_date' => Carbon::parse('2025-03-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Solar Dryers and Drying Facilities Network',
                    'description' => 'Installation of 50 solar dryers (10 tons capacity each) for cacao, coffee, copra, and fish. Includes greenhouse-type dryers, mechanical backup dryers, and moisture meters. Improves product quality and reduces drying time by 50%.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Post-Harvest Facilities']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Tandag']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Bongtud',
                    'budget' => 35000000.00,
                    'start_date' => Carbon::parse('2024-02-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Multi-Purpose Warehouses and Trading Posts',
                    'description' => 'Construction of 8 multi-purpose warehouses (500 tons each) with attached trading posts. Climate-controlled storage, fumigation facilities, grading areas, and weighing systems. Serves as collection and distribution hubs.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Post-Harvest Facilities']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bislig']->id ?? null,
                    'province_id' => $provinces['Surigao del Sur']->id ?? null,
                    'barangay' => 'Mangagoy',
                    'budget' => 52000000.00,
                    'start_date' => Carbon::parse('2024-01-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Slaughterhouse and Meat Processing Facilities',
                    'description' => 'Construction of 3 NMIS-accredited slaughterhouses (50 heads/day capacity each) and meat processing centers. Includes cold chain facilities, meat cutting rooms, waste treatment, and veterinary inspection areas.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Post-Harvest Facilities']->id ?? null,
                    'project_status_id' => $projectStatuses['Planning']->id ?? null,
                    'municipality_id' => $municipalities['Butuan']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Banza',
                    'budget' => 75000000.00,
                    'start_date' => Carbon::parse('2025-04-01'),
                    'end_date' => Carbon::parse('2027-03-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // FARM MECHANIZATION (3 projects)
                [
                    'title' => 'Agricultural Machinery Distribution Program',
                    'description' => 'Distribution of farm equipment to cooperatives: 50 hand tractors, 20 four-wheel tractors, 30 rice transplanters, 40 mechanical dryers, 50 threshers, and 25 combine harvesters. Includes operator training and maintenance services.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Farm Mechanization']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Bayugan']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'Poblacion',
                    'budget' => 72000000.00,
                    'start_date' => Carbon::parse('2024-01-15'),
                    'end_date' => Carbon::parse('2025-06-30'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Farm Machinery Service Centers and Repair Shops',
                    'description' => 'Establishment of 5 farm machinery service centers with repair shops, spare parts inventory, and trained mechanics. Mobile repair units (10 vehicles) for on-farm services. Ensures machinery uptime and proper maintenance.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Prosperidad']->id ?? null,
                    'province_id' => $provinces['Agusan del Sur']->id ?? null,
                    'barangay' => 'La Caridad',
                    'budget' => 38000000.00,
                    'start_date' => Carbon::parse('2024-03-01'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Precision Agriculture Equipment and Technology',
                    'description' => 'Introduction of precision agriculture tools: 20 GPS-guided tractors, 15 drone sprayers, soil testing kits (100 units), weather stations (30 units), and farm management software. Training on precision farming techniques.',
                    'department_id' => $departments['Regional Agricultural and Biosystems Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Farm Mechanization']->id ?? null,
                    'project_status_id' => $projectStatuses['Under Review']->id ?? null,
                    'municipality_id' => $municipalities['Surigao City']->id ?? null,
                    'province_id' => $provinces['Surigao del Norte']->id ?? null,
                    'barangay' => 'Washington',
                    'budget' => 58000000.00,
                    'start_date' => Carbon::parse('2025-02-01'),
                    'end_date' => Carbon::parse('2026-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                // WATER MANAGEMENT (1 project)
                [
                    'title' => 'Rainwater Harvesting and Farm Ponds Development',
                    'description' => 'Construction of 200 farm ponds (average 500 cubic meters each) for rainwater harvesting and supplemental irrigation. Includes pond lining, water filtration, and fish cage integration. Serves 2,000 hectares during dry season.',
                    'department_id' => $departments['Agricultural Engineering Division']->id ?? null,
                    'sector_id' => $iem?->id,
                    'project_type_id' => $projectTypes['Infrastructure Development']->id ?? null,
                    'project_status_id' => $projectStatuses['On Track']->id ?? null,
                    'municipality_id' => $municipalities['Cabadbaran']->id ?? null,
                    'province_id' => $provinces['Agusan del Norte']->id ?? null,
                    'barangay' => 'Del Pilar',
                    'budget' => 42000000.00,
                    'start_date' => Carbon::parse('2024-02-15'),
                    'end_date' => Carbon::parse('2025-12-31'),
                    'is_public' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];

            foreach ($projects as $projectData) {
                Project::create($projectData);
            }
        });

        $this->command->info('50 realistic CARAGA projects seeded successfully! (32 ES + 18 IEM)');
    }
}
